<?php

namespace Madflow\Markdown;

require_once dirname(__FILE__) . '/../src/Madflow/Markdown/Parser.php';
require_once dirname(__FILE__) . '/PhpMarkdown.php';

/**
 * Test class for Parser.
 * Generated by PHPUnit on 2011-06-14 at 16:02:04.
 */
class ExternalTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Parser
     */
    protected $object;
    
    protected $michelf;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Parser;
        //$this->michelf = new \Markdown_Parser();
    }

    public function testExternalCases()
    {
        $dir = dirname(__FILE__).'/data/external';
        $markdownFiles = glob($dir.'/*.text');
        foreach ($markdownFiles as $file)
        {
            $expected = file_get_contents($file.'.html');
            $actual = $this->object->transform(file_get_contents($file));
            $this->assertSame($expected, $actual);
        }
    }
}
