<?php

namespace Madflow\Markdown;

require_once dirname(__FILE__) . '/../src/Madflow/Markdown/Parser.php';
require_once dirname(__FILE__) . '/PhpMarkdown.php';

/**
 * Test class for Parser.
 * Generated by PHPUnit on 2011-06-14 at 16:02:04.
 */
class ParserTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Parser
     */
    protected $object;
    
    protected $michelf;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Parser;
        $this->michelf = new \Markdown_Parser();
    }

    public function testStandards()
    {
        $xml = simplexml_load_file(dirname(__FILE__).'/data/standard.xml');
        
        foreach ($xml->item as $item) 
        {
            foreach($item->markdown->definition as $definition)
            {
                $expected = (string)$item->expected;
                $actual = trim((string)$definition);
                $actual = str_replace('\n', PHP_EOL, $actual);
                $parsedActual = trim($this->object->transform($actual));
                $this->assertSame($expected, $parsedActual);
            }
        }      
    }
    
    public function testFile()
    {
        $content = file_get_contents(dirname(__FILE__).'/data/Markdown.md');
        $contentHtml = file_get_contents(dirname(__FILE__).'/data/Markdown.html');
        $parsedActual = $this->object->transform($content);
        $this->assertSame($contentHtml, $parsedActual);
    }    
}
